name            = "The Old Republic Project"; // Title of your mod as it appears in the launcher.
author          = "Stim, Moose, & Anorexican"; // Author name displayed in the launcher when mod is locally installed. If the mod is loaded from the workshop, this is overridden by the name of the workshop owner.
logo            = "tor_logo.paa"; // 128x128px .paa file displayed at the bottom of the main menu.
logoOver        = "tor_logo_over.paa"; // 128x128px .paa file that replaces logo on mouseover.
logoSmall       = "tor_logo_small.paa"; // 64x64px .paa file displayed by mod-related features (ex: next to items in the arsenal).
tooltip         = "Old Republic Project"; // Tooltip displayed on mouseover at the bottom of the main menu.
tooltipOwned    = "Old Republic Project"; // Seems to offer the same functionality as tooltip, but who knows. Definitely not me.
picture         = "tor_thumbnail.paa"; // .paa image displayed when viewing mod details in expansion menu. Optimal size is 2048x1024px.
actionName      = "Discord"; // Name of the action button in the expansion menu. Opens the URL defined in the action parameter.
action          = "https://discord.gg/XmwwbxUqjC"; // URL opened when the action button is clicked.
overview        = "Armor and equipment from the Old Republic era."; // More detailed description of the mod, located in the expansions menu. Supports structured text.
hideName        = 0; // Hides the mod name in the extension menu.
hidePicture     = 0; // Hide the thumbnail in the extension menu.
dlcColor[]      = {0.23,0.39,0.30,1}; // Color used for DLC stripes and backgrounds. (RGBA)