name = "Old Republic Project"
prefix = "tor"
mainprefix = "x"

[version]
git_hash = 0

[files]
include = [
    "*.dll",
    "*.so",
    "*.paa",
    "mod.cpp",
    "LICENSE",
    "MODDER_README.txt",
    "README.md",
]